/*
=========================================================
FILE: models.ts (Interfaces / Data Models)
=========================================================

PURPOSE:
--------
This file defines all core data structures (models) used
across the Hospital ERP frontend.

These interfaces act as:
- Type contracts between frontend ↔ backend
- Structure for API responses
- Data models for forms, tables, and services

---------------------------------------------------------

WHY INTERFACES (NOT CLASSES)?
-----------------------------
- Lightweight (no runtime overhead)
- Used only for type checking (compile-time safety)
- Perfect for DTOs (Data Transfer Objects)

---------------------------------------------------------

KEY DESIGN PRINCIPLES:
----------------------
- Strong typing (TypeScript)
- Reusability across modules
- Backend-aligned structure
- Optional fields (?) for flexibility
- Enum-like union types for controlled values

=========================================================
*/


/*
=========================================================
GENERIC API RESPONSE
=========================================================

PURPOSE:
--------
Standard wrapper for all backend responses.

Example Backend Response:
{
  data: {...},
  success: true,
  message: "Patient created successfully",
  timestamp: "2026-04-25T10:00:00"
}

WHY GENERIC <T>?
----------------
- Allows reuse for ANY data type
- Example:
  ApiResponse<Patient>
  ApiResponse<Doctor[]>

=========================================================
*/
export interface ApiResponse<T> {
  data: T;              // Actual response data (generic)
  success: boolean;     // Indicates success/failure
  message: string;      // User-friendly message
  timestamp: string;    // Server response time
}


/*
=========================================================
AUTHENTICATION MODELS
=========================================================
*/

/*
AUTH REQUEST:
-------------
Used when user logs in.

Sent to backend:
POST /login

{
  username: "...",
  password: "..."
}
*/
export interface AuthRequest {
  username: string;
  password: string;
}


/*
AUTH RESPONSE:
--------------
Received after successful login.

Contains JWT token + user info
*/
export interface AuthResponse {
  token: string;     // JWT token (used for authorization)
  username: string;  // Logged-in user
  role: string;      // Role (ADMIN, DOCTOR, etc.)
}


/*
=========================================================
PATIENT MODEL
=========================================================

Represents a patient entity in the system.

USED IN:
- Patient registration form
- Patient list view
- Appointment linking
- Billing

NOTES:
- id is optional → because new patient won't have ID yet
- gender uses union type → restricts invalid values

=========================================================
*/
export interface Patient {
  id?: number;  // Optional (generated by backend)

  firstName: string;
  lastName: string;

  dateOfBirth: string; // ISO string (YYYY-MM-DD)

  gender?: 'MALE' | 'FEMALE' | 'OTHER'; // Controlled values

  phone?: string;
  email?: string;
  address?: string;

  bloodGroup?: string;
  medicalHistory?: string;
}


/*
=========================================================
DOCTOR MODEL
=========================================================

Represents a doctor in hospital.

RELATIONSHIPS:
- Linked with appointments
- May be linked with a user account (userId)

=========================================================
*/
export interface Doctor {
  id?: number;

  firstName: string;
  lastName: string;

  specialization: string;   // e.g., Cardiologist
  licenseNumber: string;    // Unique medical license

  email?: string;
  phone?: string;

  qualification?: string;
  bio?: string;

  available: boolean;       // Used for scheduling

  userId?: number;          // Link to authentication system
}


/*
=========================================================
APPOINTMENT MODEL
=========================================================

Represents booking between Patient and Doctor.

RELATIONSHIPS:
- patientId → Patient
- doctorId → Doctor

NOTE:
- patientName, doctorName are denormalized fields
  (used for UI display, not required in DB)

=========================================================
*/
export interface Appointment {
  id?: number;

  patientId: number;   // Foreign key
  doctorId: number;    // Foreign key

  appointmentDateTime: string; // ISO datetime

  status?: 
    | 'SCHEDULED'
    | 'CONFIRMED'
    | 'COMPLETED'
    | 'CANCELLED'
    | 'NO_SHOW';  // Enum-like control

  reason?: string;
  notes?: string;

  // UI helper fields (optional)
  patientName?: string;
  doctorName?: string;
  doctorSpecialization?: string;
}


/*
=========================================================
INVOICE ITEM MODEL
=========================================================

Represents individual line item in billing.

EXAMPLE:
- Consultation fee
- Medicine charge
- Lab test

=========================================================
*/
export interface InvoiceItem {
  description: string;

  quantity: number;
  unitPrice: number;

  itemType?:
    | 'CONSULTATION'
    | 'MEDICINE'
    | 'LAB_TEST'
    | 'PROCEDURE'
    | 'ROOM_CHARGE'
    | 'OTHER';
}


/*
=========================================================
INVOICE MODEL
=========================================================

Represents billing for a patient.

RELATIONSHIPS:
- patientId → Patient
- appointmentId → Appointment
- items → InvoiceItem[]

BUSINESS LOGIC (BACKEND):
- totalAmount = sum(items)
- paymentStatus determines payment state

=========================================================
*/
export interface Invoice {
  id?: number;

  patientId: number;
  appointmentId?: number;

  items: InvoiceItem[];  // Composition (has-many relation)

  totalAmount?: number;
  paidAmount?: number;

  paymentStatus?:
    | 'PENDING'
    | 'PARTIAL'
    | 'PAID'
    | 'CANCELLED';

  paymentMethod?:
    | 'CASH'
    | 'CARD'
    | 'UPI'
    | 'INSURANCE'
    | 'ONLINE';

  patientName?: string; // UI helper
}


/*
=========================================================
MEDICINE MODEL
=========================================================

Represents pharmacy inventory item.

USED IN:
- Pharmacy module
- Billing (medicine charges)

=========================================================
*/
export interface Medicine {
  id?: number;

  name: string;

  manufacturer?: string;
  category?: string;

  price: number;           // Per unit price
  stockQuantity: number;   // Inventory tracking

  expiryDate?: string;
  batchNumber?: string;

  active: boolean;         // Whether available for use/sale
}


/*
=========================================================
SUMMARY (IMPORTANT FOR YOU)
=========================================================

You just built a COMPLETE DOMAIN MODEL layer.

This connects:
- Frontend UI
- Backend APIs
- Business logic

Think of this file as:
👉 "Blueprint of your entire ERP system"

=========================================================
*/